info:
  build:
    artifact: Haxb-Outsource-Xie
    name: Haxb-Outsource-Xie
    description: 信保个人代理人
    version: uat

# database
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.23.10:6033/haxb_agent_uat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: haxb_agent_uat
    password: faon0911
    initialSize: 30
    minIdle: 5
    maxActive: 100
    maxWait: 5000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    removeAbandoned: true
    removeAbandonedTimeout: 600
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  rabbitmq:
    virtual-host: /xb-credit-app
    host: 10.1.109.183
    port: 5672
    username: xb_credit_app
    password: credit2017
  mail:
    host: ds.sinosafe.com.cn
    username: gjzxdk@ds.sinosafe.com.cn
    password: Sno@afe18#
    properties:
      mail:
        mime.splitlongparameters: false
        smtp:
          port: 7250
          auth: true
          starttls:
            enable: false
            required: false
  redis:
    cluster:
      nodes:
      - 10.2.108.40:7000
      - 10.2.108.40:7001
      - 10.2.108.40:7002
      - 10.2.108.40:7003
      - 10.2.108.40:7004
      - 10.2.108.40:7005
      max-redirects: 3
    password: 123456
    # 缓存模块
    cache:
      redis:
        time-to-live: 1800000
